/**
 * Seed LinguaPlay problems (MVP set). Run after migrations: node --env-file=.env ./node_modules/tsx/dist/cli.mjs scripts/seed-language-problems.ts
 * Targets ~20 per level for vocabulary and grammar (MVP). Skips if table already has data (idempotent).
 */
import { db } from "../server/db";
import { languageProblems } from "@shared/schema";

const SAMPLE_PROBLEMS = [
  // Level 1: vocabulary (10) + grammar (10)
  { level: 1, mode: "vocabulary", promptEs: "Gato en inglés es:", promptEn: "Cat in Spanish is:", options: ["dog", "cat", "bird", "fish"], correctAnswer: "cat", explanationEs: "Cat = Gato", explanationEn: "Cat = Gato", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Perro en inglés es:", promptEn: "Dog in Spanish is:", options: ["cat", "dog", "horse", "cow"], correctAnswer: "dog", explanationEs: "Dog = Perro", explanationEn: "Dog = Perro", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Agua en inglés es:", promptEn: "Water in Spanish is:", options: ["fire", "water", "earth", "air"], correctAnswer: "water", explanationEs: "Water = Agua", explanationEn: "Water = Agua", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Libro en inglés es:", promptEn: "Book in Spanish is:", options: ["book", "pen", "paper", "desk"], correctAnswer: "book", explanationEs: "Book = Libro", explanationEn: "Book = Libro", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Casa en inglés es:", promptEn: "House in Spanish is:", options: ["house", "car", "tree", "sun"], correctAnswer: "house", explanationEs: "House = Casa", explanationEn: "House = Casa", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Sol en inglés es:", promptEn: "Sun in Spanish is:", options: ["moon", "sun", "star", "sky"], correctAnswer: "sun", explanationEs: "Sun = Sol", explanationEn: "Sun = Sol", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Manzana en inglés es:", promptEn: "Apple in Spanish is:", options: ["apple", "orange", "banana", "grape"], correctAnswer: "apple", explanationEs: "Apple = Manzana", explanationEn: "Apple = Manzana", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Madre en inglés es:", promptEn: "Mother in Spanish is:", options: ["father", "mother", "sister", "brother"], correctAnswer: "mother", explanationEs: "Mother = Madre", explanationEn: "Mother = Madre", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Amigo en inglés es:", promptEn: "Friend in Spanish is:", options: ["friend", "enemy", "teacher", "student"], correctAnswer: "friend", explanationEs: "Friend = Amigo", explanationEn: "Friend = Amigo", audioUrl: null },
  { level: 1, mode: "vocabulary", promptEs: "Tiempo en inglés es:", promptEn: "Time in Spanish is:", options: ["time", "day", "year", "hour"], correctAnswer: "time", explanationEs: "Time = Tiempo", explanationEn: "Time = Tiempo", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "The cat ___ very fast.", promptEn: "El gato ___ muy rápido.", options: ["run", "runs", "running", "ran"], correctAnswer: "runs", explanationEs: "Singular 'cat' usa 'runs'", explanationEn: "Singular 'cat' uses 'runs'", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "They ___ to school.", promptEn: "Ellos ___ a la escuela.", options: ["go", "goes", "going", "went"], correctAnswer: "go", explanationEs: "They = plural, verbo sin -s", explanationEn: "They = plural, verb without -s", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "He ___ breakfast every morning.", promptEn: "Él ___ desayuno cada mañana.", options: ["eat", "eats", "eating", "eaten"], correctAnswer: "eats", explanationEs: "He/She/It + verbo con -s", explanationEn: "He/She/It + verb with -s", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "I ___ English.", promptEn: "Yo ___ inglés.", options: ["study", "studies", "studying", "studied"], correctAnswer: "study", explanationEs: "I/You/We/They sin -s", explanationEn: "I/You/We/They without -s", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "She ___ music.", promptEn: "Ella ___ música.", options: ["like", "likes", "liking", "liked"], correctAnswer: "likes", explanationEs: "She + likes (tercera persona)", explanationEn: "She + likes (third person)", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "We ___ soccer.", promptEn: "Nosotros ___ fútbol.", options: ["play", "plays", "playing", "played"], correctAnswer: "play", explanationEs: "We = plural, play sin -s", explanationEn: "We = plural, play without -s", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "The dog ___ in the garden.", promptEn: "El perro ___ en el jardín.", options: ["run", "runs", "running", "ran"], correctAnswer: "runs", explanationEs: "The dog = singular, runs", explanationEn: "The dog = singular, runs", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "My brother ___ TV.", promptEn: "Mi hermano ___ televisión.", options: ["watch", "watches", "watching", "watched"], correctAnswer: "watches", explanationEs: "My brother = he, watches (con -es)", explanationEn: "My brother = he, watches (with -es)", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "You ___ a good student.", promptEn: "Tú ___ un buen estudiante.", options: ["is", "are", "am", "be"], correctAnswer: "are", explanationEs: "You + are", explanationEn: "You + are", audioUrl: null },
  { level: 1, mode: "grammar", promptEs: "It ___ cold today.", promptEn: "___ frío hoy.", options: ["is", "are", "am", "be"], correctAnswer: "is", explanationEs: "It/He/She + is", explanationEn: "It/He/She + is", audioUrl: null },
  // Level 2: vocabulary (10) + grammar (10)
  { level: 2, mode: "vocabulary", promptEs: "¿Cómo estás? en inglés:", promptEn: "How are you? in Spanish:", options: ["What is your name?", "How are you?", "Where are you?", "When is it?"], correctAnswer: "How are you?", explanationEs: "How are you? = ¿Cómo estás?", explanationEn: "How are you? = ¿Cómo estás?", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Bathroom en español:", promptEn: "Baño en inglés:", options: ["bedroom", "bathroom", "kitchen", "living room"], correctAnswer: "bathroom", explanationEs: "Bathroom = Baño", explanationEn: "Bathroom = Baño", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Good morning en español:", promptEn: "Buenos días en inglés:", options: ["Good night", "Good morning", "Good afternoon", "Good evening"], correctAnswer: "Good morning", explanationEs: "Good morning = Buenos días", explanationEn: "Good morning = Buenos días", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Thank you en español:", promptEn: "Gracias en inglés:", options: ["Please", "Thank you", "Sorry", "Hello"], correctAnswer: "Thank you", explanationEs: "Thank you = Gracias", explanationEn: "Thank you = Gracias", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Where is the...? en español:", promptEn: "¿Dónde está...? en inglés:", options: ["What is...?", "Where is...?", "When is...?", "Who is...?"], correctAnswer: "Where is...?", explanationEs: "Where is...? = ¿Dónde está...?", explanationEn: "Where is...? = ¿Dónde está...?", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Money en español:", promptEn: "Dinero en inglés:", options: ["money", "cash", "coin", "bill"], correctAnswer: "money", explanationEs: "Money = Dinero", explanationEn: "Money = Dinero", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Please en español:", promptEn: "Por favor en inglés:", options: ["Thanks", "Please", "Sorry", "Yes"], correctAnswer: "Please", explanationEs: "Please = Por favor", explanationEn: "Please = Por favor", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Food en español:", promptEn: "Comida en inglés:", options: ["food", "drink", "water", "meal"], correctAnswer: "food", explanationEs: "Food = Comida", explanationEn: "Food = Comida", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "Work en español:", promptEn: "Trabajo en inglés:", options: ["work", "job", "office", "career"], correctAnswer: "work", explanationEs: "Work = Trabajo", explanationEn: "Work = Trabajo", audioUrl: null },
  { level: 2, mode: "vocabulary", promptEs: "School en español:", promptEn: "Escuela en inglés:", options: ["school", "university", "college", "class"], correctAnswer: "school", explanationEs: "School = Escuela", explanationEn: "School = Escuela", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "She ___ a book every day.", promptEn: "Ella ___ un libro cada día.", options: ["read", "reads", "reading", "reader"], correctAnswer: "reads", explanationEs: "She + verbo en presente: reads", explanationEn: "She + present verb: reads", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "They ___ to the store.", promptEn: "Ellos ___ a la tienda.", options: ["go", "goes", "going", "gone"], correctAnswer: "go", explanationEs: "They + go (plural)", explanationEn: "They + go (plural)", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "My sister ___ dancing.", promptEn: "Mi hermana ___ bailar.", options: ["like", "likes", "liking", "liked"], correctAnswer: "likes", explanationEs: "My sister = she, likes", explanationEn: "My sister = she, likes", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "We ___ homework.", promptEn: "Nosotros ___ tarea.", options: ["have", "has", "having", "had"], correctAnswer: "have", explanationEs: "We + have", explanationEn: "We + have", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "He ___ a car.", promptEn: "Él ___ un carro.", options: ["have", "has", "having", "had"], correctAnswer: "has", explanationEs: "He/She/It + has", explanationEn: "He/She/It + has", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "I ___ a question.", promptEn: "Yo ___ una pregunta.", options: ["have", "has", "having", "had"], correctAnswer: "have", explanationEs: "I/You/We/They + have", explanationEn: "I/You/We/They + have", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "The book ___ on the table.", promptEn: "El libro ___ en la mesa.", options: ["is", "are", "am", "be"], correctAnswer: "is", explanationEs: "The book = singular, is", explanationEn: "The book = singular, is", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "There ___ many students.", promptEn: "___ muchos estudiantes.", options: ["is", "are", "am", "be"], correctAnswer: "are", explanationEs: "many students = plural, are", explanationEn: "many students = plural, are", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "She ___ to work by bus.", promptEn: "Ella ___ al trabajo en bus.", options: ["travel", "travels", "travelling", "travelled"], correctAnswer: "travels", explanationEs: "She + travels", explanationEn: "She + travels", audioUrl: null },
  { level: 2, mode: "grammar", promptEs: "They ___ coffee.", promptEn: "Ellos ___ café.", options: ["drink", "drinks", "drinking", "drank"], correctAnswer: "drink", explanationEs: "They + drink (plural)", explanationEn: "They + drink (plural)", audioUrl: null },
  // Level 3–6: 10 vocab + 10 grammar each (80 more)
  { level: 3, mode: "vocabulary", promptEs: "Verbo 'to run' en pasado:", promptEn: "Past tense of 'run':", options: ["run", "runs", "ran", "running"], correctAnswer: "ran", explanationEs: "run → ran (irregular)", explanationEn: "run → ran (irregular)", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "Verbo 'to eat' en pasado:", promptEn: "Past tense of 'eat':", options: ["eat", "eats", "ate", "eaten"], correctAnswer: "ate", explanationEs: "eat → ate (irregular)", explanationEn: "eat → ate (irregular)", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "Yesterday en español:", promptEn: "Ayer en inglés:", options: ["today", "yesterday", "tomorrow", "now"], correctAnswer: "yesterday", explanationEs: "Yesterday = Ayer", explanationEn: "Yesterday = Ayer", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "Tomorrow en español:", promptEn: "Mañana en inglés:", options: ["today", "yesterday", "tomorrow", "later"], correctAnswer: "tomorrow", explanationEs: "Tomorrow = Mañana", explanationEn: "Tomorrow = Mañana", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "To go en pasado:", promptEn: "Past of 'go':", options: ["go", "goes", "went", "gone"], correctAnswer: "went", explanationEs: "go → went (irregular)", explanationEn: "go → went (irregular)", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "To see en pasado:", promptEn: "Past of 'see':", options: ["see", "sees", "saw", "seen"], correctAnswer: "saw", explanationEs: "see → saw (irregular)", explanationEn: "see → saw (irregular)", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "To write en pasado:", promptEn: "Past of 'write':", options: ["write", "writes", "wrote", "written"], correctAnswer: "wrote", explanationEs: "write → wrote (irregular)", explanationEn: "write → wrote (irregular)", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "To buy en pasado:", promptEn: "Past of 'buy':", options: ["buy", "buys", "bought", "boughten"], correctAnswer: "bought", explanationEs: "buy → bought (irregular)", explanationEn: "buy → bought (irregular)", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "To make en pasado:", promptEn: "Past of 'make':", options: ["make", "makes", "made", "maked"], correctAnswer: "made", explanationEs: "make → made (irregular)", explanationEn: "make → made (irregular)", audioUrl: null },
  { level: 3, mode: "vocabulary", promptEs: "To think en pasado:", promptEn: "Past of 'think':", options: ["think", "thinks", "thought", "thinking"], correctAnswer: "thought", explanationEs: "think → thought (irregular)", explanationEn: "think → thought (irregular)", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "I ___ to school yesterday.", promptEn: "Yo ___ a la escuela ayer.", options: ["go", "goes", "went", "going"], correctAnswer: "went", explanationEs: "Pasado de go = went", explanationEn: "Past of go = went", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "She ___ the movie last night.", promptEn: "Ella ___ la película anoche.", options: ["watch", "watches", "watched", "watching"], correctAnswer: "watched", explanationEs: "Pasado regular: watched", explanationEn: "Regular past: watched", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "They ___ home early.", promptEn: "Ellos ___ a casa temprano.", options: ["come", "comes", "came", "coming"], correctAnswer: "came", explanationEs: "come → came (irregular)", explanationEn: "come → came (irregular)", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "He ___ his homework.", promptEn: "Él ___ su tarea.", options: ["finish", "finishes", "finished", "finishing"], correctAnswer: "finished", explanationEs: "Pasado regular: -ed", explanationEn: "Regular past: -ed", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "We ___ pizza for dinner.", promptEn: "Nosotros ___ pizza para cenar.", options: ["eat", "eats", "ate", "eaten"], correctAnswer: "ate", explanationEs: "eat → ate", explanationEn: "eat → ate", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "I ___ a letter.", promptEn: "Yo ___ una carta.", options: ["write", "writes", "wrote", "written"], correctAnswer: "wrote", explanationEs: "write → wrote", explanationEn: "write → wrote", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "She ___ to the store.", promptEn: "Ella ___ a la tienda.", options: ["go", "goes", "went", "gone"], correctAnswer: "went", explanationEs: "go → went", explanationEn: "go → went", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "They ___ the game.", promptEn: "Ellos ___ el juego.", options: ["see", "sees", "saw", "seen"], correctAnswer: "saw", explanationEs: "see → saw", explanationEn: "see → saw", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "He ___ a new car.", promptEn: "Él ___ un carro nuevo.", options: ["buy", "buys", "bought", "buying"], correctAnswer: "bought", explanationEs: "buy → bought", explanationEn: "buy → bought", audioUrl: null },
  { level: 3, mode: "grammar", promptEs: "We ___ dinner together.", promptEn: "Nosotros ___ la cena juntos.", options: ["make", "makes", "made", "making"], correctAnswer: "made", explanationEs: "make → made", explanationEn: "make → made", audioUrl: null },
  // Level 4
  { level: 4, mode: "vocabulary", promptEs: "Futuro con 'will': I ___ go.", promptEn: "Future with will: I ___ go.", options: ["will", "would", "went", "go"], correctAnswer: "will", explanationEs: "will + verbo base", explanationEn: "will + base verb", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "Would like en español:", promptEn: "Me gustaría en inglés:", options: ["I want", "I would like", "I need", "I prefer"], correctAnswer: "I would like", explanationEs: "Would like = gustaría", explanationEn: "Would like = gustaría", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "Should en español:", promptEn: "Debería en inglés:", options: ["can", "should", "must", "could"], correctAnswer: "should", explanationEs: "Should = debería (consejo)", explanationEn: "Should = ought to (advice)", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "Could (pasado de can):", promptEn: "Could as past of can:", options: ["can", "could", "would", "might"], correctAnswer: "could", explanationEs: "Could = podía / podría", explanationEn: "Could = was able to / might", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "To be able to:", promptEn: "Poder (ser capaz):", options: ["can", "could", "be able to", "may"], correctAnswer: "be able to", explanationEs: "be able to = poder (formal)", explanationEn: "be able to = can (formal)", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "Already en español:", promptEn: "Ya en inglés:", options: ["yet", "already", "still", "just"], correctAnswer: "already", explanationEs: "Already = ya (afirmativo)", explanationEn: "Already = ya (affirmative)", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "Yet (negativo/pregunta):", promptEn: "Aún no / ¿Ya?:", options: ["already", "yet", "still", "just"], correctAnswer: "yet", explanationEs: "Yet = aún no, ¿ya?", explanationEn: "Yet = not yet, already?", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "Although en español:", promptEn: "Aunque en inglés:", options: ["but", "although", "however", "because"], correctAnswer: "although", explanationEs: "Although = aunque", explanationEn: "Although = aunque", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "Therefore en español:", promptEn: "Por tanto en inglés:", options: ["because", "therefore", "however", "although"], correctAnswer: "therefore", explanationEs: "Therefore = por tanto", explanationEn: "Therefore = por tanto", audioUrl: null },
  { level: 4, mode: "vocabulary", promptEs: "However en español:", promptEn: "Sin embargo en inglés:", options: ["but", "however", "although", "because"], correctAnswer: "however", explanationEs: "However = sin embargo", explanationEn: "However = sin embargo", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "I ___ call you tomorrow.", promptEn: "Yo ___ te llamo mañana.", options: ["will", "would", "went", "go"], correctAnswer: "will", explanationEs: "Futuro con will", explanationEn: "Future with will", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "She ___ like to help.", promptEn: "Ella ___ gustaría ayudar.", options: ["will", "would", "could", "can"], correctAnswer: "would", explanationEs: "would like = gustaría", explanationEn: "would like = gustaría", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "You ___ see a doctor.", promptEn: "Tú ___ ver a un médico.", options: ["can", "should", "must", "would"], correctAnswer: "should", explanationEs: "should = consejo", explanationEn: "should = advice", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "When I was young, I ___ run fast.", promptEn: "Cuando era joven, ___ correr rápido.", options: ["can", "could", "will", "would"], correctAnswer: "could", explanationEs: "could = pasado de can", explanationEn: "could = past of can", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "They ___ already left.", promptEn: "Ellos ___ ya se fueron.", options: ["have", "has", "had", "having"], correctAnswer: "have", explanationEs: "They + have", explanationEn: "They + have", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "She ___ not finished yet.", promptEn: "Ella ___ no ha terminado aún.", options: ["have", "has", "had", "having"], correctAnswer: "has", explanationEs: "She + has", explanationEn: "She + has", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "___ it was cold, we went out.", promptEn: "___ hacía frío, salimos.", options: ["But", "Although", "Because", "So"], correctAnswer: "Although", explanationEs: "Although = aunque", explanationEn: "Although = though", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "I have ___ seen that movie.", promptEn: "Ya ___ vi esa película.", options: ["yet", "already", "still", "just"], correctAnswer: "already", explanationEs: "already en afirmativo", explanationEn: "already in affirmative", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "Have you finished ___?", promptEn: "¿Has terminado ___?", options: ["already", "yet", "still", "just"], correctAnswer: "yet", explanationEs: "yet en pregunta", explanationEn: "yet in question", audioUrl: null },
  { level: 4, mode: "grammar", promptEs: "We ___ be there at 8.", promptEn: "Nosotros ___ estar ahí a las 8.", options: ["will", "would", "could", "can"], correctAnswer: "will", explanationEs: "will = futuro", explanationEn: "will = future", audioUrl: null },
  // Level 5
  { level: 5, mode: "vocabulary", promptEs: "Meeting (reunión) en español:", promptEn: "Reunión en inglés:", options: ["meeting", "conference", "appointment", "session"], correctAnswer: "meeting", explanationEs: "Meeting = reunión", explanationEn: "Meeting = reunión", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "Deadline en español:", promptEn: "Fecha límite en inglés:", options: ["deadline", "schedule", "date", "time"], correctAnswer: "deadline", explanationEs: "Deadline = fecha límite", explanationEn: "Deadline = fecha límite", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "Budget en español:", promptEn: "Presupuesto en inglés:", options: ["budget", "money", "cost", "price"], correctAnswer: "budget", explanationEs: "Budget = presupuesto", explanationEn: "Budget = presupuesto", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "To schedule en español:", promptEn: "Programar / agendar:", options: ["schedule", "plan", "organize", "arrange"], correctAnswer: "schedule", explanationEs: "To schedule = programar", explanationEn: "To schedule = programar", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "Feedback en español:", promptEn: "Retroalimentación en inglés:", options: ["feedback", "comment", "review", "opinion"], correctAnswer: "feedback", explanationEs: "Feedback = retroalimentación", explanationEn: "Feedback = retroalimentación", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "To apply (aplicar) en contexto laboral:", promptEn: "Aplicar a un trabajo:", options: ["apply", "request", "ask", "submit"], correctAnswer: "apply", explanationEs: "To apply = postularse, aplicar", explanationEn: "To apply = to apply for a job", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "Resume (CV) en español:", promptEn: "Currículum en inglés:", options: ["resume", "letter", "application", "form"], correctAnswer: "resume", explanationEs: "Resume = currículum", explanationEn: "Resume = CV", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "To hire en español:", promptEn: "Contratar en inglés:", options: ["hire", "fire", "work", "employ"], correctAnswer: "hire", explanationEs: "To hire = contratar", explanationEn: "To hire = contratar", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "Salary en español:", promptEn: "Salario en inglés:", options: ["salary", "wage", "pay", "income"], correctAnswer: "salary", explanationEs: "Salary = salario", explanationEn: "Salary = salario", audioUrl: null },
  { level: 5, mode: "vocabulary", promptEs: "To negotiate en español:", promptEn: "Negociar en inglés:", options: ["negotiate", "discuss", "agree", "decide"], correctAnswer: "negotiate", explanationEs: "To negotiate = negociar", explanationEn: "To negotiate = negociar", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "If I ___ rich, I would travel.", promptEn: "Si yo ___ rico, viajaría.", options: ["am", "was", "were", "be"], correctAnswer: "were", explanationEs: "Segundo condicional: were (subjuntivo)", explanationEn: "Second conditional: were (subjunctive)", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "I wish she ___ here.", promptEn: "Ojalá ella ___ aquí.", options: ["is", "was", "were", "be"], correctAnswer: "were", explanationEs: "I wish + pasado subjuntivo (were)", explanationEn: "I wish + past subjunctive (were)", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "The report ___ by the manager.", promptEn: "El reporte ___ por el gerente.", options: ["write", "wrote", "was written", "written"], correctAnswer: "was written", explanationEs: "Voz pasiva: was + participio", explanationEn: "Passive voice: was + past participle", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "She suggested ___ early.", promptEn: "Ella sugirió ___ temprano.", options: ["leave", "to leave", "leaving", "left"], correctAnswer: "leaving", explanationEs: "suggest + -ing", explanationEn: "suggest + -ing", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "He asked me ___ I was ready.", promptEn: "Él me preguntó ___ estaba listo.", options: ["if", "that", "what", "when"], correctAnswer: "if", explanationEs: "ask + if (sí/no)", explanationEn: "ask + if (yes/no)", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "Despite ___ tired, she continued.", promptEn: "A pesar de ___ cansada, continuó.", options: ["be", "being", "been", "was"], correctAnswer: "being", explanationEs: "Despite + -ing", explanationEn: "Despite + -ing", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "The project ___ completed.", promptEn: "El proyecto ___ completado.", options: ["has been", "have been", "has", "have"], correctAnswer: "has been", explanationEs: "Present perfect passive", explanationEn: "Present perfect passive", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "I look forward to ___ you.", promptEn: "Espero ___ verte.", options: ["see", "seeing", "seen", "saw"], correctAnswer: "seeing", explanationEs: "look forward to + -ing", explanationEn: "look forward to + -ing", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "Neither John ___ Mary came.", promptEn: "Ni John ___ Mary vinieron.", options: ["or", "nor", "and", "but"], correctAnswer: "nor", explanationEs: "Neither... nor", explanationEn: "Neither... nor", audioUrl: null },
  { level: 5, mode: "grammar", promptEs: "Not only ___ she sing, but she also dances.", promptEn: "No solo ___ canta, sino que también baila.", options: ["does", "do", "is", "has"], correctAnswer: "does", explanationEs: "Not only... but (inversión)", explanationEn: "Not only... but (inversion)", audioUrl: null },
  // Level 6
  { level: 6, mode: "vocabulary", promptEs: "Stakeholder en español:", promptEn: "Interesado / parte interesada:", options: ["stakeholder", "shareholder", "partner", "client"], correctAnswer: "stakeholder", explanationEs: "Stakeholder = parte interesada", explanationEn: "Stakeholder = interested party", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "To leverage en español:", promptEn: "Aprovechar / potenciar:", options: ["leverage", "use", "take", "get"], correctAnswer: "leverage", explanationEs: "To leverage = aprovechar recursos", explanationEn: "To leverage = to use effectively", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "Benchmark en español:", promptEn: "Referencia / comparación:", options: ["benchmark", "standard", "goal", "target"], correctAnswer: "benchmark", explanationEs: "Benchmark = punto de referencia", explanationEn: "Benchmark = reference point", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "To streamline en español:", promptEn: "Optimizar / simplificar:", options: ["streamline", "improve", "change", "fix"], correctAnswer: "streamline", explanationEs: "To streamline = optimizar procesos", explanationEn: "To streamline = optimize", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "Compliance en español:", promptEn: "Cumplimiento normativo:", options: ["compliance", "rule", "law", "policy"], correctAnswer: "compliance", explanationEs: "Compliance = cumplimiento", explanationEn: "Compliance = cumplimiento", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "To allocate en español:", promptEn: "Asignar / asignar recursos:", options: ["allocate", "give", "put", "send"], correctAnswer: "allocate", explanationEs: "To allocate = asignar", explanationEn: "To allocate = to assign", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "Scope (alcance) en proyecto:", promptEn: "Alcance en inglés:", options: ["scope", "range", "limit", "size"], correctAnswer: "scope", explanationEs: "Scope = alcance del proyecto", explanationEn: "Scope = project scope", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "To submit (entregar) en formal:", promptEn: "Entregar (formal):", options: ["submit", "send", "give", "hand"], correctAnswer: "submit", explanationEs: "To submit = entregar formalmente", explanationEn: "To submit = to hand in", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "Due diligence en español:", promptEn: "Debida diligencia:", options: ["due diligence", "research", "check", "audit"], correctAnswer: "due diligence", explanationEs: "Due diligence = debida diligencia", explanationEn: "Due diligence = debida diligencia", audioUrl: null },
  { level: 6, mode: "vocabulary", promptEs: "Quarter (trimestre) en negocio:", promptEn: "Trimestre en inglés:", options: ["quarter", "month", "year", "period"], correctAnswer: "quarter", explanationEs: "Quarter = trimestre (Q1, Q2...)", explanationEn: "Quarter = trimestre (Q1, Q2...)", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "It is essential that he ___ on time.", promptEn: "Es esencial que él ___ a tiempo.", options: ["arrive", "arrives", "arrived", "arriving"], correctAnswer: "arrive", explanationEs: "Subjuntivo: essential that + base", explanationEn: "Subjunctive: essential that + base", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "The committee ___ that the proposal be accepted.", promptEn: "El comité ___ que la propuesta sea aceptada.", options: ["recommend", "recommends", "recommended", "recommending"], correctAnswer: "recommends", explanationEs: "recommend + that + subjuntivo", explanationEn: "recommend + that + subjunctive", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "Had I known, I ___ have come.", promptEn: "De haber sabido, ___ habría venido.", options: ["will", "would", "could", "should"], correctAnswer: "would", explanationEs: "Tercer condicional invertido", explanationEn: "Third conditional inverted", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "The data ___ been analyzed.", promptEn: "Los datos ___ sido analizados.", options: ["has", "have", "had", "having"], correctAnswer: "have", explanationEs: "data = plural (datos)", explanationEn: "data = plural (datos)", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "Neither the manager ___ the team was available.", promptEn: "Ni el gerente ___ el equipo estaba disponible.", options: ["or", "nor", "and", "but"], correctAnswer: "nor", explanationEs: "Neither... nor + verbo (segundo sujeto)", explanationEn: "Neither... nor + verb (second subject)", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "It is requested that all documents ___ submitted.", promptEn: "Se solicita que todos los documentos ___ entregados.", options: ["be", "are", "were", "been"], correctAnswer: "be", explanationEs: "requested that + subjuntivo (be)", explanationEn: "requested that + subjunctive (be)", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "The results, ___ were surprising, were published.", promptEn: "Los resultados, ___ fueron sorprendentes, se publicaron.", options: ["that", "which", "who", "whom"], correctAnswer: "which", explanationEs: "which en cláusula no restrictiva", explanationEn: "which in non-restrictive clause", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "___ consideration of the above, we agree.", promptEn: "___ consideración de lo anterior, estamos de acuerdo.", options: ["In", "On", "At", "For"], correctAnswer: "In", explanationEs: "In consideration of = en consideración", explanationEn: "In consideration of = en consideración", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "The report is ___ to be published.", promptEn: "El reporte está ___ ser publicado.", options: ["due", "expected", "likely", "bound"], correctAnswer: "due", explanationEs: "due to be = por publicarse", explanationEn: "due to be = scheduled to be", audioUrl: null },
  { level: 6, mode: "grammar", promptEs: "We ___ our position in the market.", promptEn: "Nosotros ___ nuestra posición en el mercado.", options: ["strengthen", "strengthens", "strengthened", "strengthening"], correctAnswer: "strengthen", explanationEs: "We + strengthen (present)", explanationEn: "We + strengthen (present)", audioUrl: null },
];

async function seed() {
  const existing = await db.select().from(languageProblems);
  if (existing.length > 0) {
    console.log(`language_problems already has ${existing.length} rows. Skipping seed.`);
    return;
  }
  console.log("Seeding language_problems...");
  await db.insert(languageProblems).values(SAMPLE_PROBLEMS);
  const count = await db.select().from(languageProblems);
  console.log(`Done. Total language_problems: ${count.length}`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
