/**
 * Seed MathMaster problems (MVP set). Run after migrations: node --env-file=.env ./node_modules/tsx/dist/cli.mjs scripts/seed-math-problems.ts
 * Targets 120+ problems (~20 per level). Skips if table already has data (idempotent).
 */
import { db } from "../server/db";
import { mathProblems } from "@shared/schema";

const SAMPLE_PROBLEMS = [
  // Level 1: Basic Arithmetic (20)
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 5 + 3?", questionEn: "What is 5 + 3?", options: ["6", "7", "8", "9"], correctAnswer: "8", explanationEs: "5 + 3 = 8", explanationEn: "5 + 3 = 8", category: "addition" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 10 - 4?", questionEn: "What is 10 - 4?", options: ["5", "6", "7", "8"], correctAnswer: "6", explanationEs: "10 - 4 = 6", explanationEn: "10 - 4 = 6", category: "subtraction" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 4 × 3?", questionEn: "What is 4 × 3?", options: ["10", "11", "12", "13"], correctAnswer: "12", explanationEs: "4 × 3 = 12", explanationEn: "4 × 3 = 12", category: "multiplication" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 15 ÷ 3?", questionEn: "What is 15 ÷ 3?", options: ["3", "4", "5", "6"], correctAnswer: "5", explanationEs: "15 ÷ 3 = 5", explanationEn: "15 ÷ 3 = 5", category: "division" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 7 + 9?", questionEn: "What is 7 + 9?", options: ["15", "16", "17", "18"], correctAnswer: "16", explanationEs: "7 + 9 = 16", explanationEn: "7 + 9 = 16", category: "addition" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 12 - 5?", questionEn: "What is 12 - 5?", options: ["6", "7", "8", "9"], correctAnswer: "7", explanationEs: "12 - 5 = 7", explanationEn: "12 - 5 = 7", category: "subtraction" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 6 × 4?", questionEn: "What is 6 × 4?", options: ["20", "22", "24", "26"], correctAnswer: "24", explanationEs: "6 × 4 = 24", explanationEn: "6 × 4 = 24", category: "multiplication" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 18 ÷ 6?", questionEn: "What is 18 ÷ 6?", options: ["2", "3", "4", "5"], correctAnswer: "3", explanationEs: "18 ÷ 6 = 3", explanationEn: "18 ÷ 6 = 3", category: "division" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 8 + 7?", questionEn: "What is 8 + 7?", options: ["14", "15", "16", "17"], correctAnswer: "15", explanationEs: "8 + 7 = 15", explanationEn: "8 + 7 = 15", category: "addition" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 14 - 8?", questionEn: "What is 14 - 8?", options: ["5", "6", "7", "8"], correctAnswer: "6", explanationEs: "14 - 8 = 6", explanationEn: "14 - 8 = 6", category: "subtraction" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 5 × 5?", questionEn: "What is 5 × 5?", options: ["20", "25", "30", "35"], correctAnswer: "25", explanationEs: "5 × 5 = 25", explanationEn: "5 × 5 = 25", category: "multiplication" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 24 ÷ 4?", questionEn: "What is 24 ÷ 4?", options: ["4", "5", "6", "7"], correctAnswer: "6", explanationEs: "24 ÷ 4 = 6", explanationEn: "24 ÷ 4 = 6", category: "division" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 11 + 9?", questionEn: "What is 11 + 9?", options: ["18", "19", "20", "21"], correctAnswer: "20", explanationEs: "11 + 9 = 20", explanationEn: "11 + 9 = 20", category: "addition" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 16 - 9?", questionEn: "What is 16 - 9?", options: ["6", "7", "8", "9"], correctAnswer: "7", explanationEs: "16 - 9 = 7", explanationEn: "16 - 9 = 7", category: "subtraction" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 7 × 3?", questionEn: "What is 7 × 3?", options: ["20", "21", "22", "23"], correctAnswer: "21", explanationEs: "7 × 3 = 21", explanationEn: "7 × 3 = 21", category: "multiplication" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 20 ÷ 5?", questionEn: "What is 20 ÷ 5?", options: ["3", "4", "5", "6"], correctAnswer: "4", explanationEs: "20 ÷ 5 = 4", explanationEn: "20 ÷ 5 = 4", category: "division" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 13 + 8?", questionEn: "What is 13 + 8?", options: ["20", "21", "22", "23"], correctAnswer: "21", explanationEs: "13 + 8 = 21", explanationEn: "13 + 8 = 21", category: "addition" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 17 - 8?", questionEn: "What is 17 - 8?", options: ["8", "9", "10", "11"], correctAnswer: "9", explanationEs: "17 - 8 = 9", explanationEn: "17 - 8 = 9", category: "subtraction" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 9 × 2?", questionEn: "What is 9 × 2?", options: ["16", "18", "20", "22"], correctAnswer: "18", explanationEs: "9 × 2 = 18", explanationEn: "9 × 2 = 18", category: "multiplication" },
  { level: 1, topic: "arithmetic", questionEs: "¿Cuánto es 28 ÷ 7?", questionEn: "What is 28 ÷ 7?", options: ["3", "4", "5", "6"], correctAnswer: "4", explanationEs: "28 ÷ 7 = 4", explanationEn: "28 ÷ 7 = 4", category: "division" },
  // Level 2: Fractions & Decimals (20)
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 1/2 + 1/4?", questionEn: "What is 1/2 + 1/4?", options: ["1/4", "2/6", "3/4", "1"], correctAnswer: "3/4", explanationEs: "1/2 = 2/4, entonces 2/4 + 1/4 = 3/4", explanationEn: "1/2 = 2/4, so 2/4 + 1/4 = 3/4", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.5 × 2?", questionEn: "What is 0.5 × 2?", options: ["0.5", "1", "1.5", "2"], correctAnswer: "1", explanationEs: "0.5 × 2 = 1", explanationEn: "0.5 × 2 = 1", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 3/4 - 1/4?", questionEn: "What is 3/4 - 1/4?", options: ["1/2", "1/4", "2/4", "1"], correctAnswer: "1/2", explanationEs: "3/4 - 1/4 = 2/4 = 1/2", explanationEn: "3/4 - 1/4 = 2/4 = 1/2", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 1/3 + 1/3?", questionEn: "What is 1/3 + 1/3?", options: ["1/6", "2/3", "2/6", "1"], correctAnswer: "2/3", explanationEs: "1/3 + 1/3 = 2/3", explanationEn: "1/3 + 1/3 = 2/3", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.25 + 0.25?", questionEn: "What is 0.25 + 0.25?", options: ["0.25", "0.5", "0.75", "1"], correctAnswer: "0.5", explanationEs: "0.25 + 0.25 = 0.5", explanationEn: "0.25 + 0.25 = 0.5", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 2/5 + 1/5?", questionEn: "What is 2/5 + 1/5?", options: ["1/5", "3/10", "3/5", "1"], correctAnswer: "3/5", explanationEs: "2/5 + 1/5 = 3/5", explanationEn: "2/5 + 1/5 = 3/5", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.1 × 10?", questionEn: "What is 0.1 × 10?", options: ["0.1", "1", "10", "100"], correctAnswer: "1", explanationEs: "0.1 × 10 = 1", explanationEn: "0.1 × 10 = 1", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 4/5 - 2/5?", questionEn: "What is 4/5 - 2/5?", options: ["1/5", "2/5", "2/10", "1"], correctAnswer: "2/5", explanationEs: "4/5 - 2/5 = 2/5", explanationEn: "4/5 - 2/5 = 2/5", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.75 - 0.25?", questionEn: "What is 0.75 - 0.25?", options: ["0.25", "0.5", "0.75", "1"], correctAnswer: "0.5", explanationEs: "0.75 - 0.25 = 0.5", explanationEn: "0.75 - 0.25 = 0.5", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 1/2 × 2?", questionEn: "What is 1/2 × 2?", options: ["1/2", "1", "2", "4"], correctAnswer: "1", explanationEs: "1/2 × 2 = 1", explanationEn: "1/2 × 2 = 1", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 1/4 + 1/4 + 1/4?", questionEn: "What is 1/4 + 1/4 + 1/4?", options: ["1/12", "2/4", "3/4", "1"], correctAnswer: "3/4", explanationEs: "1/4 + 1/4 + 1/4 = 3/4", explanationEn: "1/4 + 1/4 + 1/4 = 3/4", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.2 + 0.3?", questionEn: "What is 0.2 + 0.3?", options: ["0.1", "0.5", "0.6", "5"], correctAnswer: "0.5", explanationEs: "0.2 + 0.3 = 0.5", explanationEn: "0.2 + 0.3 = 0.5", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 5/6 - 1/6?", questionEn: "What is 5/6 - 1/6?", options: ["1/3", "2/3", "4/6", "1"], correctAnswer: "2/3", explanationEs: "5/6 - 1/6 = 4/6 = 2/3", explanationEn: "5/6 - 1/6 = 4/6 = 2/3", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.5 + 0.5?", questionEn: "What is 0.5 + 0.5?", options: ["0.5", "1", "1.5", "2"], correctAnswer: "1", explanationEs: "0.5 + 0.5 = 1", explanationEn: "0.5 + 0.5 = 1", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 1/2 de 8?", questionEn: "What is 1/2 of 8?", options: ["2", "4", "6", "8"], correctAnswer: "4", explanationEs: "1/2 × 8 = 4", explanationEn: "1/2 × 8 = 4", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.4 × 5?", questionEn: "What is 0.4 × 5?", options: ["1", "2", "2.5", "20"], correctAnswer: "2", explanationEs: "0.4 × 5 = 2", explanationEn: "0.4 × 5 = 2", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 3/8 + 2/8?", questionEn: "What is 3/8 + 2/8?", options: ["1/8", "5/16", "5/8", "1"], correctAnswer: "5/8", explanationEs: "3/8 + 2/8 = 5/8", explanationEn: "3/8 + 2/8 = 5/8", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 1 - 0.3?", questionEn: "What is 1 - 0.3?", options: ["0.3", "0.7", "1.3", "7"], correctAnswer: "0.7", explanationEs: "1 - 0.3 = 0.7", explanationEn: "1 - 0.3 = 0.7", category: "decimals" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 2/3 - 1/3?", questionEn: "What is 2/3 - 1/3?", options: ["1/6", "1/3", "1/2", "1"], correctAnswer: "1/3", explanationEs: "2/3 - 1/3 = 1/3", explanationEn: "2/3 - 1/3 = 1/3", category: "fractions" },
  { level: 2, topic: "fractions", questionEs: "¿Cuánto es 0.6 ÷ 2?", questionEn: "What is 0.6 ÷ 2?", options: ["0.2", "0.3", "0.6", "1.2"], correctAnswer: "0.3", explanationEs: "0.6 ÷ 2 = 0.3", explanationEn: "0.6 ÷ 2 = 0.3", category: "decimals" },
  // Level 3: Algebra (20)
  { level: 3, topic: "algebra", questionEs: "Si 2x + 3 = 7, ¿cuánto es x?", questionEn: "If 2x + 3 = 7, what is x?", options: ["1", "2", "3", "4"], correctAnswer: "2", explanationEs: "2x = 7 - 3 = 4, entonces x = 2", explanationEn: "2x = 7 - 3 = 4, so x = 2", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x - 5 = 10, ¿cuánto es x?", questionEn: "If x - 5 = 10, what is x?", options: ["5", "10", "15", "20"], correctAnswer: "15", explanationEs: "x = 10 + 5 = 15", explanationEn: "x = 10 + 5 = 15", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 3x = 12, ¿cuánto es x?", questionEn: "If 3x = 12, what is x?", options: ["3", "4", "6", "9"], correctAnswer: "4", explanationEs: "3x = 12 → x = 4", explanationEn: "3x = 12 → x = 4", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x + 7 = 15, ¿cuánto es x?", questionEn: "If x + 7 = 15, what is x?", options: ["6", "7", "8", "9"], correctAnswer: "8", explanationEs: "x = 15 - 7 = 8", explanationEn: "x = 15 - 7 = 8", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 5x - 5 = 20, ¿cuánto es x?", questionEn: "If 5x - 5 = 20, what is x?", options: ["3", "4", "5", "6"], correctAnswer: "5", explanationEs: "5x = 25 → x = 5", explanationEn: "5x = 25 → x = 5", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 2x - 4 = 6, ¿cuánto es x?", questionEn: "If 2x - 4 = 6, what is x?", options: ["3", "4", "5", "6"], correctAnswer: "5", explanationEs: "2x = 10 → x = 5", explanationEn: "2x = 10 → x = 5", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x/2 = 5, ¿cuánto es x?", questionEn: "If x/2 = 5, what is x?", options: ["2", "5", "7", "10"], correctAnswer: "10", explanationEs: "x = 5 × 2 = 10", explanationEn: "x = 5 × 2 = 10", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 4 + x = 11, ¿cuánto es x?", questionEn: "If 4 + x = 11, what is x?", options: ["5", "6", "7", "8"], correctAnswer: "7", explanationEs: "x = 11 - 4 = 7", explanationEn: "x = 11 - 4 = 7", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 6x = 18, ¿cuánto es x?", questionEn: "If 6x = 18, what is x?", options: ["2", "3", "4", "6"], correctAnswer: "3", explanationEs: "6x = 18 → x = 3", explanationEn: "6x = 18 → x = 3", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x - 3 = 9, ¿cuánto es x?", questionEn: "If x - 3 = 9, what is x?", options: ["6", "9", "12", "15"], correctAnswer: "12", explanationEs: "x = 9 + 3 = 12", explanationEn: "x = 9 + 3 = 12", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 3x + 2 = 14, ¿cuánto es x?", questionEn: "If 3x + 2 = 14, what is x?", options: ["3", "4", "5", "6"], correctAnswer: "4", explanationEs: "3x = 12 → x = 4", explanationEn: "3x = 12 → x = 4", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x/3 = 4, ¿cuánto es x?", questionEn: "If x/3 = 4, what is x?", options: ["7", "12", "15", "16"], correctAnswer: "12", explanationEs: "x = 4 × 3 = 12", explanationEn: "x = 4 × 3 = 12", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 2x + 5 = 13, ¿cuánto es x?", questionEn: "If 2x + 5 = 13, what is x?", options: ["3", "4", "5", "6"], correctAnswer: "4", explanationEs: "2x = 8 → x = 4", explanationEn: "2x = 8 → x = 4", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x + 12 = 20, ¿cuánto es x?", questionEn: "If x + 12 = 20, what is x?", options: ["6", "7", "8", "9"], correctAnswer: "8", explanationEs: "x = 20 - 12 = 8", explanationEn: "x = 20 - 12 = 8", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 4x - 8 = 12, ¿cuánto es x?", questionEn: "If 4x - 8 = 12, what is x?", options: ["3", "4", "5", "6"], correctAnswer: "5", explanationEs: "4x = 20 → x = 5", explanationEn: "4x = 20 → x = 5", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 7x = 21, ¿cuánto es x?", questionEn: "If 7x = 21, what is x?", options: ["2", "3", "4", "7"], correctAnswer: "3", explanationEs: "7x = 21 → x = 3", explanationEn: "7x = 21 → x = 3", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x - 6 = 4, ¿cuánto es x?", questionEn: "If x - 6 = 4, what is x?", options: ["2", "4", "10", "12"], correctAnswer: "10", explanationEs: "x = 4 + 6 = 10", explanationEn: "x = 4 + 6 = 10", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 5x + 1 = 16, ¿cuánto es x?", questionEn: "If 5x + 1 = 16, what is x?", options: ["2", "3", "4", "5"], correctAnswer: "3", explanationEs: "5x = 15 → x = 3", explanationEn: "5x = 15 → x = 3", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si x/4 = 5, ¿cuánto es x?", questionEn: "If x/4 = 5, what is x?", options: ["9", "15", "20", "25"], correctAnswer: "20", explanationEs: "x = 5 × 4 = 20", explanationEn: "x = 5 × 4 = 20", category: "algebra" },
  { level: 3, topic: "algebra", questionEs: "Si 8 + x = 17, ¿cuánto es x?", questionEn: "If 8 + x = 17, what is x?", options: ["8", "9", "10", "11"], correctAnswer: "9", explanationEs: "x = 17 - 8 = 9", explanationEn: "x = 17 - 8 = 9", category: "algebra" },
  // Level 4: Geometry (20)
  { level: 4, topic: "geometry", questionEs: "Área de un rectángulo 5 × 4:", questionEn: "Area of a rectangle 5 × 4:", options: ["9", "18", "20", "25"], correctAnswer: "20", explanationEs: "Área = base × altura = 5 × 4 = 20", explanationEn: "Area = base × height = 5 × 4 = 20", category: "area" },
  { level: 4, topic: "geometry", questionEs: "Perímetro de un cuadrado de lado 6:", questionEn: "Perimeter of a square with side 6:", options: ["12", "24", "36", "48"], correctAnswer: "24", explanationEs: "Perímetro = 4 × lado = 4 × 6 = 24", explanationEn: "Perimeter = 4 × side = 4 × 6 = 24", category: "perimeter" },
  { level: 4, topic: "geometry", questionEs: "Área de un triángulo base 6, altura 4:", questionEn: "Area of triangle base 6, height 4:", options: ["10", "12", "24", "48"], correctAnswer: "12", explanationEs: "Área = (base × altura)/2 = 24/2 = 12", explanationEn: "Area = (base × height)/2 = 24/2 = 12", category: "area" },
  { level: 4, topic: "geometry", questionEs: "En un triángulo rectángulo con catetos 3 y 4, ¿hipotenusa?", questionEn: "In a right triangle with legs 3 and 4, hypotenuse?", options: ["5", "6", "7", "12"], correctAnswer: "5", explanationEs: "Teorema de Pitágoras: 3² + 4² = 9 + 16 = 25 = 5²", explanationEn: "Pythagorean theorem: 3² + 4² = 25 = 5²", category: "pythagorean" },
  { level: 4, topic: "geometry", questionEs: "Perímetro de rectángulo 7 × 3:", questionEn: "Perimeter of rectangle 7 × 3:", options: ["10", "20", "21", "42"], correctAnswer: "20", explanationEs: "Perímetro = 2(7+3) = 20", explanationEn: "Perimeter = 2(7+3) = 20", category: "perimeter" },
  { level: 4, topic: "geometry", questionEs: "Área de un círculo con radio 3 (π ≈ 3.14):", questionEn: "Area of circle radius 3 (π ≈ 3.14):", options: ["9π", "6π", "3π", "π"], correctAnswer: "9π", explanationEs: "Área = πr² = π(3)² = 9π", explanationEn: "Area = πr² = π(3)² = 9π", category: "area" },
  { level: 4, topic: "geometry", questionEs: "Suma de ángulos internos de un triángulo:", questionEn: "Sum of interior angles of a triangle:", options: ["90°", "180°", "270°", "360°"], correctAnswer: "180°", explanationEs: "Todo triángulo tiene 180° internos", explanationEn: "Every triangle has 180° interior sum", category: "angles" },
  { level: 4, topic: "geometry", questionEs: "Área de rectángulo 8 × 2:", questionEn: "Area of rectangle 8 × 2:", options: ["10", "16", "20", "32"], correctAnswer: "16", explanationEs: "8 × 2 = 16", explanationEn: "8 × 2 = 16", category: "area" },
  { level: 4, topic: "geometry", questionEs: "Perímetro de triángulo con lados 3, 4, 5:", questionEn: "Perimeter of triangle sides 3, 4, 5:", options: ["12", "15", "60", "120"], correctAnswer: "12", explanationEs: "3 + 4 + 5 = 12", explanationEn: "3 + 4 + 5 = 12", category: "perimeter" },
  { level: 4, topic: "geometry", questionEs: "Catetos 6 y 8, ¿hipotenusa?", questionEn: "Legs 6 and 8, hypotenuse?", options: ["10", "14", "28", "100"], correctAnswer: "10", explanationEs: "6² + 8² = 36 + 64 = 100 = 10²", explanationEn: "6² + 8² = 100 = 10²", category: "pythagorean" },
  { level: 4, topic: "geometry", questionEs: "Área de triángulo base 10, altura 5:", questionEn: "Area of triangle base 10, height 5:", options: ["15", "25", "50", "100"], correctAnswer: "25", explanationEs: "(10 × 5)/2 = 25", explanationEn: "(10 × 5)/2 = 25", category: "area" },
  { level: 4, topic: "geometry", questionEs: "Un ángulo recto mide:", questionEn: "A right angle measures:", options: ["45°", "90°", "180°", "360°"], correctAnswer: "90°", explanationEs: "Ángulo recto = 90°", explanationEn: "Right angle = 90°", category: "angles" },
  { level: 4, topic: "geometry", questionEs: "Perímetro de cuadrado lado 5:", questionEn: "Perimeter of square side 5:", options: ["10", "20", "25", "50"], correctAnswer: "20", explanationEs: "4 × 5 = 20", explanationEn: "4 × 5 = 20", category: "perimeter" },
  { level: 4, topic: "geometry", questionEs: "Área rectángulo 6 × 5:", questionEn: "Area rectangle 6 × 5:", options: ["11", "22", "30", "56"], correctAnswer: "30", explanationEs: "6 × 5 = 30", explanationEn: "6 × 5 = 30", category: "area" },
  { level: 4, topic: "geometry", questionEs: "Catetos 5 y 12, hipotenusa:", questionEn: "Legs 5 and 12, hypotenuse:", options: ["13", "17", "60", "169"], correctAnswer: "13", explanationEs: "5² + 12² = 25 + 144 = 169 = 13²", explanationEn: "5² + 12² = 169 = 13²", category: "pythagorean" },
  { level: 4, topic: "geometry", questionEs: "Perímetro rectángulo 4 × 9:", questionEn: "Perimeter rectangle 4 × 9:", options: ["13", "26", "36", "72"], correctAnswer: "26", explanationEs: "2(4+9) = 26", explanationEn: "2(4+9) = 26", category: "perimeter" },
  { level: 4, topic: "geometry", questionEs: "Área triángulo base 8, altura 6:", questionEn: "Area triangle base 8, height 6:", options: ["14", "24", "48", "96"], correctAnswer: "24", explanationEs: "(8×6)/2 = 24", explanationEn: "(8×6)/2 = 24", category: "area" },
  { level: 4, topic: "geometry", questionEs: "Suma ángulos de un cuadrilátero:", questionEn: "Sum of angles in a quadrilateral:", options: ["180°", "270°", "360°", "720°"], correctAnswer: "360°", explanationEs: "Todo cuadrilátero tiene 360°", explanationEn: "Every quadrilateral has 360°", category: "angles" },
  { level: 4, topic: "geometry", questionEs: "Área círculo radio 5 (en términos de π):", questionEn: "Area circle radius 5 (in terms of π):", options: ["5π", "10π", "25π", "50π"], correctAnswer: "25π", explanationEs: "πr² = π(5)² = 25π", explanationEn: "πr² = π(5)² = 25π", category: "area" },
  { level: 4, topic: "geometry", questionEs: "Perímetro triángulo equilátero lado 6:", questionEn: "Perimeter of equilateral triangle side 6:", options: ["6", "12", "18", "36"], correctAnswer: "18", explanationEs: "3 × 6 = 18", explanationEn: "3 × 6 = 18", category: "perimeter" },
  // Level 5: Pre-Calculus (20)
  { level: 5, topic: "precalculus", questionEs: "sen(30°) =", questionEn: "sin(30°) =", options: ["0", "1/2", "√2/2", "1"], correctAnswer: "1/2", explanationEs: "sen(30°) = 1/2", explanationEn: "sin(30°) = 1/2", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "cos(0°) =", questionEn: "cos(0°) =", options: ["0", "1/2", "1", "√2/2"], correctAnswer: "1", explanationEs: "cos(0°) = 1", explanationEn: "cos(0°) = 1", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "2³ × 2² =", questionEn: "2³ × 2² =", options: ["4", "16", "32", "64"], correctAnswer: "32", explanationEs: "2³ × 2² = 2⁵ = 32", explanationEn: "2³ × 2² = 2⁵ = 32", category: "exponents" },
  { level: 5, topic: "precalculus", questionEs: "log₁₀(100) =", questionEn: "log₁₀(100) =", options: ["1", "2", "10", "100"], correctAnswer: "2", explanationEs: "10² = 100 → log₁₀(100) = 2", explanationEn: "10² = 100 → log₁₀(100) = 2", category: "logarithms" },
  { level: 5, topic: "precalculus", questionEs: "tan(45°) =", questionEn: "tan(45°) =", options: ["0", "1", "√2", "√3"], correctAnswer: "1", explanationEs: "tan(45°) = 1", explanationEn: "tan(45°) = 1", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "3² × 3³ =", questionEn: "3² × 3³ =", options: ["9", "27", "81", "243"], correctAnswer: "243", explanationEs: "3² × 3³ = 3⁵ = 243", explanationEn: "3² × 3³ = 3⁵ = 243", category: "exponents" },
  { level: 5, topic: "precalculus", questionEs: "sen(90°) =", questionEn: "sin(90°) =", options: ["0", "1/2", "√2/2", "1"], correctAnswer: "1", explanationEs: "sen(90°) = 1", explanationEn: "sin(90°) = 1", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "log₂(8) =", questionEn: "log₂(8) =", options: ["2", "3", "4", "8"], correctAnswer: "3", explanationEs: "2³ = 8 → log₂(8) = 3", explanationEn: "2³ = 8 → log₂(8) = 3", category: "logarithms" },
  { level: 5, topic: "precalculus", questionEs: "5⁰ =", questionEn: "5⁰ =", options: ["0", "1", "5", "50"], correctAnswer: "1", explanationEs: "Cualquier número⁰ = 1", explanationEn: "Any number⁰ = 1", category: "exponents" },
  { level: 5, topic: "precalculus", questionEs: "cos(60°) =", questionEn: "cos(60°) =", options: ["0", "1/2", "√2/2", "1"], correctAnswer: "1/2", explanationEs: "cos(60°) = 1/2", explanationEn: "cos(60°) = 1/2", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "2⁴ ÷ 2² =", questionEn: "2⁴ ÷ 2² =", options: ["2", "4", "8", "16"], correctAnswer: "4", explanationEs: "2⁴ ÷ 2² = 2² = 4", explanationEn: "2⁴ ÷ 2² = 2² = 4", category: "exponents" },
  { level: 5, topic: "precalculus", questionEs: "log₁₀(10) =", questionEn: "log₁₀(10) =", options: ["0", "1", "10", "100"], correctAnswer: "1", explanationEs: "10¹ = 10 → log₁₀(10) = 1", explanationEn: "10¹ = 10 → log₁₀(10) = 1", category: "logarithms" },
  { level: 5, topic: "precalculus", questionEs: "sen(0°) =", questionEn: "sin(0°) =", options: ["0", "1/2", "1", "√2/2"], correctAnswer: "0", explanationEs: "sen(0°) = 0", explanationEn: "sin(0°) = 0", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "(2²)³ =", questionEn: "(2²)³ =", options: ["2⁵", "2⁶", "2⁸", "64"], correctAnswer: "2⁶", explanationEs: "(2²)³ = 2⁶ = 64", explanationEn: "(2²)³ = 2⁶ = 64", category: "exponents" },
  { level: 5, topic: "precalculus", questionEs: "cos(90°) =", questionEn: "cos(90°) =", options: ["0", "1/2", "1", "√2/2"], correctAnswer: "0", explanationEs: "cos(90°) = 0", explanationEn: "cos(90°) = 0", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "log₃(9) =", questionEn: "log₃(9) =", options: ["1", "2", "3", "9"], correctAnswer: "2", explanationEs: "3² = 9 → log₃(9) = 2", explanationEn: "3² = 9 → log₃(9) = 2", category: "logarithms" },
  { level: 5, topic: "precalculus", questionEs: "10² =", questionEn: "10² =", options: ["20", "100", "200", "1000"], correctAnswer: "100", explanationEs: "10² = 100", explanationEn: "10² = 100", category: "exponents" },
  { level: 5, topic: "precalculus", questionEs: "tan(0°) =", questionEn: "tan(0°) =", options: ["0", "1", "√3", "undefined"], correctAnswer: "0", explanationEs: "tan(0°) = 0", explanationEn: "tan(0°) = 0", category: "trigonometry" },
  { level: 5, topic: "precalculus", questionEs: "2⁻¹ =", questionEn: "2⁻¹ =", options: ["-2", "0", "1/2", "2"], correctAnswer: "1/2", explanationEs: "2⁻¹ = 1/2", explanationEn: "2⁻¹ = 1/2", category: "exponents" },
  { level: 5, topic: "precalculus", questionEs: "log₅(25) =", questionEn: "log₅(25) =", options: ["1", "2", "5", "25"], correctAnswer: "2", explanationEs: "5² = 25 → log₅(25) = 2", explanationEn: "5² = 25 → log₅(25) = 2", category: "logarithms" },
  // Level 6: Calculus (20)
  { level: 6, topic: "calculus", questionEs: "Derivada de x²:", questionEn: "Derivative of x²:", options: ["x", "2x", "x²", "2"], correctAnswer: "2x", explanationEs: "d/dx(x²) = 2x", explanationEn: "d/dx(x²) = 2x", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "Derivada de x³:", questionEn: "Derivative of x³:", options: ["x²", "2x²", "3x²", "3x"], correctAnswer: "3x²", explanationEs: "d/dx(x³) = 3x²", explanationEn: "d/dx(x³) = 3x²", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "Derivada de una constante c:", questionEn: "Derivative of constant c:", options: ["c", "0", "1", "x"], correctAnswer: "0", explanationEs: "d/dx(c) = 0", explanationEn: "d/dx(c) = 0", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ 1 dx =", questionEn: "∫ 1 dx =", options: ["0", "x", "x + C", "1"], correctAnswer: "x + C", explanationEs: "∫ 1 dx = x + C", explanationEn: "∫ 1 dx = x + C", category: "integrals" },
  { level: 6, topic: "calculus", questionEs: "Derivada de x:", questionEn: "Derivative of x:", options: ["0", "1", "x", "x²/2"], correctAnswer: "1", explanationEs: "d/dx(x) = 1", explanationEn: "d/dx(x) = 1", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ x dx =", questionEn: "∫ x dx =", options: ["x²", "x²/2", "x²/2 + C", "2x"], correctAnswer: "x²/2 + C", explanationEs: "∫ x dx = x²/2 + C", explanationEn: "∫ x dx = x²/2 + C", category: "integrals" },
  { level: 6, topic: "calculus", questionEs: "Derivada de 5x:", questionEn: "Derivative of 5x:", options: ["5", "5x", "5x²", "0"], correctAnswer: "5", explanationEs: "d/dx(5x) = 5", explanationEn: "d/dx(5x) = 5", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ 2x dx =", questionEn: "∫ 2x dx =", options: ["x²", "x² + C", "2x²", "2x² + C"], correctAnswer: "x² + C", explanationEs: "∫ 2x dx = x² + C", explanationEn: "∫ 2x dx = x² + C", category: "integrals" },
  { level: 6, topic: "calculus", questionEs: "Derivada de x⁴:", questionEn: "Derivative of x⁴:", options: ["x³", "4x³", "4x⁴", "x⁴/4"], correctAnswer: "4x³", explanationEs: "d/dx(x⁴) = 4x³", explanationEn: "d/dx(x⁴) = 4x³", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "Derivada de 3x²:", questionEn: "Derivative of 3x²:", options: ["3x", "6x", "6x²", "x²"], correctAnswer: "6x", explanationEs: "d/dx(3x²) = 6x", explanationEn: "d/dx(3x²) = 6x", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ x² dx =", questionEn: "∫ x² dx =", options: ["x²", "x³", "x³/3 + C", "2x"], correctAnswer: "x³/3 + C", explanationEs: "∫ x² dx = x³/3 + C", explanationEn: "∫ x² dx = x³/3 + C", category: "integrals" },
  { level: 6, topic: "calculus", questionEs: "Derivada de 2x + 1:", questionEn: "Derivative of 2x + 1:", options: ["2", "2x", "2x + 1", "0"], correctAnswer: "2", explanationEs: "d/dx(2x+1) = 2", explanationEn: "d/dx(2x+1) = 2", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ 3x² dx =", questionEn: "∫ 3x² dx =", options: ["x³", "x³ + C", "3x³", "9x"], correctAnswer: "x³ + C", explanationEs: "∫ 3x² dx = x³ + C", explanationEn: "∫ 3x² dx = x³ + C", category: "integrals" },
  { level: 6, topic: "calculus", questionEs: "Derivada de x⁵:", questionEn: "Derivative of x⁵:", options: ["5x⁴", "x⁴", "5x⁵", "x⁵/5"], correctAnswer: "5x⁴", explanationEs: "d/dx(x⁵) = 5x⁴", explanationEn: "d/dx(x⁵) = 5x⁴", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ 4x³ dx =", questionEn: "∫ 4x³ dx =", options: ["x⁴", "x⁴ + C", "4x⁴", "12x²"], correctAnswer: "x⁴ + C", explanationEs: "∫ 4x³ dx = x⁴ + C", explanationEn: "∫ 4x³ dx = x⁴ + C", category: "integrals" },
  { level: 6, topic: "calculus", questionEs: "Derivada de -x²:", questionEn: "Derivative of -x²:", options: ["-x", "-2x", "x²", "2x"], correctAnswer: "-2x", explanationEs: "d/dx(-x²) = -2x", explanationEn: "d/dx(-x²) = -2x", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "Derivada de 7:", questionEn: "Derivative of 7:", options: ["7", "0", "7x", "1"], correctAnswer: "0", explanationEs: "d/dx(7) = 0", explanationEn: "d/dx(7) = 0", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ 5 dx =", questionEn: "∫ 5 dx =", options: ["5", "5x", "5x + C", "0"], correctAnswer: "5x + C", explanationEs: "∫ 5 dx = 5x + C", explanationEn: "∫ 5 dx = 5x + C", category: "integrals" },
  { level: 6, topic: "calculus", questionEs: "Derivada de 4x³:", questionEn: "Derivative of 4x³:", options: ["12x²", "4x²", "12x³", "x³"], correctAnswer: "12x²", explanationEs: "d/dx(4x³) = 12x²", explanationEn: "d/dx(4x³) = 12x²", category: "derivatives" },
  { level: 6, topic: "calculus", questionEs: "∫ 6x dx =", questionEn: "∫ 6x dx =", options: ["3x²", "3x² + C", "6x²", "6x² + C"], correctAnswer: "3x² + C", explanationEs: "∫ 6x dx = 3x² + C", explanationEn: "∫ 6x dx = 3x² + C", category: "integrals" },
];

async function seed() {
  const existing = await db.select().from(mathProblems);
  if (existing.length > 0) {
    console.log(`math_problems already has ${existing.length} rows. Skipping seed.`);
    return;
  }
  console.log("Seeding math_problems...");
  await db.insert(mathProblems).values(SAMPLE_PROBLEMS);
  const count = await db.select().from(mathProblems);
  console.log(`Done. Total math_problems: ${count.length}`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
